version: '3'

services:

  # postgres:
  #   image: 'postgres:14.5'
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: paswoord
  #     POSTGRES_DB: database
  #     PGDATA: /var/lib/postgresql/data/postgres-data
  #   logging:
  #     options:
  #       max-size: 100m
  #       max-file: "12"
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql
  #     - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  my-flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - .:/app

  # production_gateway_service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5051:5000"
  #   volumes:
  #     - .:/app
