data_service_api:
  title: "Circular Wood 4.0 API"
  version: 1.0.0
  description: "REST API to operate the database, processors and several workflows within the CW4.0 project goals"
  developers: 
    - "Javid Jooshesh"
    - "Mike Schardijn"
  contact: 
    - "j.jooshesh@hva.nl"
  
  external:
    apis:
      url:
        # Potentially to be an external authentication service API (WIP)
        - &dev_auth_api_url http://localhost:1993
      api_keys: []
    tools:
      idemat:
        # Internal path to the idemat json file containing environmental data of wood
        path: idemat/idenmat_2023_wood_simplified.json
    frontend_apps:
      url:  
        # This can be any frontend app being tested
        - http://localhost:3000
        # Already hosted on render.com 
        - https://robotlab-db-gui.onrender.com
  
  server:
    port: 5050
    host: 0.0.0.0
    environment:
        selected_mode: development
        modes: 
          development:
            url: http://localhost:5050
            logging: DEBUG
          production:
            hosting_system: WEB_HOSTING_SERVICE
            vendor: render.com
            url: https://robotlab-residualwood.onrender.com
            logging: INFO
  configs:
    secret_key: 4e5508fd-979d-47ad-a56b-e9a604d02f1f
    propogate_exceptions: true
    rate_limiting:
      requests_per_minute: 100
      burst: 50
    cors:
      access_control_allow_credentials: true
      allow_headers:
        - Accept
        - Content-Type
        - X-Auth-Email
        - X-Auth-Key
        - X-CSRF-Token
        - Origin
        - X-Requested-With
        - Authorization
      allowed_origins:
        - http://localhost:3000
        - https://robotlab-db-gui.onrender.com
        - http://localhost:5050
        - https://robotlab-residualwood.onrender.com
    max_content_length: 10485760 # restrict max upload content size to 10MB

  database:
    server: sqlite
    host: localhost
    port: ""
    user: ""
    password: ""
    dbname: ""
    sslmode: disable
    timezone: UTC
    connect_timeout: 5
    middleware: SQLALCHEMY
    uri: sqlite:///instance/data.db
    track_modifications: false

  documentation:
    endpoint: api-docs
    service:
      title: openapi
      openapi_version: 3.0.3
      openapi_url_prefix: /
      openapi_swagger_ui_path: /api-docs
      openapi_swagger_ui_url: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

  security:
    cookie_settings:
      same_site: Strict
      token_location: cookies
      cookie_secure: false
      csrf_in_cookies: false
      http_only: true
      
    jwt:
      secret: ROBOT-LAB_118944794548470618589981863246285508728
      issuer: https://robotlab-residualwood.onrender.com
      audience: https://robotlab-residualwood.onrender.com
      expiration_time: 3600

  logging:
    format: json
    output: stdout

  cache:
    redis:
      host: localhost
      port: 6379
      expiration_time: 86400

workflow_manager:
  api_http_client:
    clients:
      - name: DESIGN_CLIENT
  production_run:
    title: PRODUCTION_GATEWAY
    network_configuration:
      type: LAN
      settings:
        dhcp: manual
        ethernet:
          interface: eth0
          ipv4:
            dns:
              gateway_ip: 10.0.0.1
              broadcast_ip: 10.0.0.255
            subnet_mask: 255.255.255.0
    hardware_components:
      control_system:
        # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/wiki/S7-300%20documentation.aspx"
        unit: PLC
        model: SIEMENS_SIMATIC_S7-300
      equipment:
        robots:
          - title: BLUE
            # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/wiki/ABB_IRB4600-60_205_BLUE_documentation.aspx"
            controller_series: IRC5
            model: ABB_IRB4600-60_205
            device: GRIPPER
          - title: RED
            # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/wiki/ABB_IRB4600-60_205_RED_documentation.aspx"
            controller_series: IRC5
            model: ABB_IRB4600-60_205
            device: ATC
        auxiliary_devices:
          - title: LECTOR
            # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/wiki/Lector611%20barcode%20reader.aspx"
            unit: IMAGE_BASED_CODE_READER
            model: SICK_Lector61X
            commands:
              start_command: 21
              stop_command: 22
              framing:
                opening: "\x02"
                end: "\x03"
          - title: LABEL_PRINTER
            # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/wiki/HSA%20minikey%20-%20Industrial%20inkjet%20printhead.aspx"
            # commands_link: "https://icthva.sharepoint.com/sites/ft-engineering-rola/PublishingImages/wiki/Lector611%20barcode%20reader/24_11_4%20[DOCUMENTATION]%20lector%2061x%20setup-user%20guide.pdf"
            unit: THERMAL_INK_JET_PRINTER
            model: HSA_MiniKey
    communication_protocols:
      # Communication between production cell components
      ftp:
        # Instruction delivery to the robot controllers from the gateway application
        robot_configuration:
          blue_robot:
            ip: 10.0.0.13
            credentials:
              username: "Default User"
              password: "robotics"
            directory: /
          red_robot:
            ip: 10.0.0.14
            credentials:
              username: "Default User"
              password: "robotics"
            directory: /RED_MILLING
      tcp:
        # For procedure calls to devices via socket connection
        connections:
          lector:
            ip: 10.0.0.45
            ports:
              command_port: 2112
              response_port: 1024
          label_printer:
            ip: 10.0.0.77
            ports:
              command_port: 3000
              response_port: 1024
      mqtt:
        # Event broker between the database, gateway and the controllers
        # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/wiki/Mqtt%20and%20Profinet%20communications.aspx"
        broker_info:
          ip: 10.0.0.9
          port: 1883
        topics:
          production:
            - wood_data: PLC_coms/Stool/WoodID
          robots:
            from_robot_to_plc:
              blue:
                request_part_data: PLC_coms/stoolReady
              red:
                fetch_rapid:
                  - PLC_coms/Stool/CW_RAPID_Needed
                  - PLC_coms/Stool/CB_RAPID_Needed
            from_plc_to_robot:
              blue:
                request_part_data: PLC_coms/Stool/NewStoolData
              red:
                fetch_rapid:
                  - PLComs/RAPID_Fetched_Windw
                  - PLC_coms/RAPID_Fetched_Fence
          status_flags:
            pickup:
              - Stool/Status/PU_Start
              - Stool/Status/PU_Done
            centering_unit:
              - Stool/Status/CU_Drop
              - Stool/Status/CU_Pickup
            sawing:
              - Stool/Status/SAW_start
              - Stool/Status/SAW_done
            clamping:
              - Stool/Status/CW_PL
              - Stool/Status/CW_PU
              - Stool/Status/CB_PL
              - Stool/Status/CB_PU
            milling:
              - PLC_coms/status/milling/RED_CW_Milling_started
              - PLC_coms/status/milling/RED_CW_Milling_done
              - PLC_coms/status/milling/RED_CB_Milling_started
              - PLC_coms/status/milling/RED_CB_Milling_done
              - PLC_coms/status/milling/CurPart
            drop_off:
              - Stool/Status/DropOff
            process_end:
              - Stool/Status/PlankDone
          lector:
            # lector response will also be published to WoodID
            - PLC_coms/Stool/WoodID
            - PLC_coms/Stool/Scan/StartScan
      http:
        database_service:
          # Used for communication with the database API
          # documentation: "https://robotlab-residualwood.onrender.com/api-docs"
          environments:
            development:
              base_url: http://localhost:5050
            production:
              base_url: https://robotlab-residualwood.onrender.com
          credentials:
            # This field is not DSN connection string. It is only for the auth for protected routes
            username: robotlab-admin
            password: robotlab2024
          endpoints:
            post:
              authentication:
                path: "/login"
                auth_required: false
              process:
                path: "/process"
                auth_required: true
            get:
              wood_by_id:
                path: "/wood/{wood_id}"
                auth_required: false
              subwood_by_wood_id:
                path: "/subwood/wood/{wood_id}"
                auth_required: false
              production_by_wood_id:
                path: "/production/wood/{wood_id}"
                auth_required: false
              design_by_wood_id:
                path: "/design/wood/{wood_id}"
                auth_required: false
              process_by_wood_id:
                path: "/process/wood/{wood_id}"
                auth_required: true
            patch:
              wood_by_id:
                path: "/wood/{wood_id}"
                auth_required: true
              process_by_id:
                path: "/process/{process_id}"
                auth_required: true
      profinet:
        section: StoolProduction
        # documentation: "https://icthva.sharepoint.com/sites/ft-engineering-rola/Gedeelde%20documenten/[DOCUMENTATION]%202024-2025%20sem%201%20pre-makeathon%20PLC%20communications.pdf"

