api:
  title: Robotlab Database API
  version: 1.0.0
  description: "Wood Database REST API"
  
  configs:
    secret_key: 4e5508fd-979d-47ad-a56b-e9a604d02f1f
    propogate_exceptions: true

    rate_limiting:
      requests_per_minute: 100
      burst: 50

    cors:
      access_control_allow_credentials: true
      allow_headers:
        - Accept
        - Content-Type
        - X-Auth-Email
        - X-Auth-Key
        - X-CSRF-Token
        - Origin
        - X-Requested-With
        - Authorization
        
      allowed_origins:
        - http://localhost:3000
        - http://localhost:5050
        - https://robotlab-residualwood.onrender.com

    max_content_length: 10485760 # restrict max upload content size to 10MB
    upload_image_destination: "./static/img"

  database:
    server: sqlite
    host: localhost
    port: null
    user: null
    password: null
    dbname: null
    sslmode: disable
    timezone: UTC
    connect_timeout: 5
    middleware: SQLALCHEMY
    uri: sqlite:///instance/data.db
    track_modifications: false

  documentation:
    endpoint: api-docs
    service:
      title: openapi
      openapi_version: "3.0.3"
      openapi_url_prefix: "/"
      openapi_swagger_ui_path: "/api-docs"
      openapi_swagger_ui_url: "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"

  server:
    port: 5050
    host: 0.0.0.0
    environment:
        mode: development
        url: http://localhost:5050
        logging: DEBUG

  security:
    jwt:
      secret: "ROBOT-LAB_118944794548470618589981863246285508728"
      issuer: https://robotlab-residualwood.onrender.com
      audience: https://robotlab-residualwood.onrender.com
      expiration_time: 3600
      same_site: 'Strict'
      token_location: "cookies"
      cookie_secure: false
      csrf_in_cookies: true
      http_only: true

  logging:
    format: json
    output: stdout

  cache:
    redis:
      host: localhost
      port: 6379
      expiration_time: 86400
