"""improves schema

Revision ID: a8100e46d06d
Revises: 9b7b729020d3
Create Date: 2023-12-07 16:03:45.919587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8100e46d06d'
down_revision = '9b7b729020d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.String(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('length')
        batch_op.drop_column('width')
        batch_op.drop_column('height')

    with op.batch_alter_table('wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('used_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wood', schema=None) as batch_op:
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted')
        batch_op.drop_column('used_by')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.FLOAT(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('features')

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
