"""adds new filed in design

Revision ID: ab5c86f57e2d
Revises: a8100e46d06d
Create Date: 2023-12-19 16:37:24.378364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5c86f57e2d'
down_revision = 'a8100e46d06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wood_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_column('wood_id')

    # ### end Alembic commands ###
