"""added a few columns to wood_database

Revision ID: f6d46520c061
Revises: ab5c86f57e2d
Create Date: 2024-02-01 18:13:54.043017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d46520c061'
down_revision = 'ab5c86f57e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_piece', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('production_phase', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('design', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verified_measurements', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wood', schema=None) as batch_op:
        batch_op.drop_column('verified_measurements')
        batch_op.drop_column('design')
        batch_op.drop_column('production_phase')
        batch_op.drop_column('original_piece')

    # ### end Alembic commands ###
