"""empty message

Revision ID: 25edbcc07cf6
Revises: af9cc0f184df
Create Date: 2022-12-21 00:12:01.881170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25edbcc07cf6'
down_revision = 'af9cc0f184df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    with op.batch_alter_table('waste_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_wood', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
