"""adding new fields of location and wood_id

Revision ID: 29d49c9d503e
Revises: bb671a77b435
Create Date: 2023-10-05 16:11:47.484785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d49c9d503e'
down_revision = 'bb671a77b435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wood_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.drop_column('wood_id')

    # ### end Alembic commands ###
