"""empty message

Revision ID: 4cb118f5865f
Revises: 25edbcc07cf6
Create Date: 2023-05-17 14:21:25.161751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb118f5865f'
down_revision = '25edbcc07cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('part_index',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('part_index',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
