"""empty message

Revision ID: 68d04a7ca5be
Revises: 
Create Date: 2022-12-01 12:06:23.017336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d04a7ca5be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_wood_model')
    with op.batch_alter_table('wood_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contains_metal', sa.Boolean(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wood_model', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.drop_column('contains_metal')

    op.create_table('_alembic_tmp_wood_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('length', sa.FLOAT(), nullable=False),
    sa.Column('width', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('density', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=80), nullable=False),
    sa.Column('contains_metal', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
