"""clean up

Revision ID: 6f93fbea5717
Revises: 6d35601b87cf
Create Date: 2023-11-28 17:28:23.862369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f93fbea5717'
down_revision = '6d35601b87cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_wood')
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_metal', sa.Boolean(), nullable=True))
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('density',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('label')
        batch_op.drop_column('wood_id')
        batch_op.drop_column('wood_species')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wood_species', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('wood_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('has_metal')
        batch_op.drop_column('project_label')

    op.create_table('waste_wood',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('length', sa.FLOAT(), nullable=False),
    sa.Column('width', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('density', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=80), nullable=False),
    sa.Column('damaged', sa.BOOLEAN(), nullable=False),
    sa.Column('stained', sa.BOOLEAN(), nullable=False),
    sa.Column('contains_metal', sa.BOOLEAN(), nullable=False),
    sa.Column('reserved', sa.BOOLEAN(), nullable=True),
    sa.Column('reservation_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('reservation_time', sa.VARCHAR(length=80), nullable=True),
    sa.Column('source', sa.VARCHAR(length=256), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('info', sa.VARCHAR(length=256), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_waste_wood')
    )
    # ### end Alembic commands ###
