"""schema correction - requirements

Revision ID: 7b50aa3d4815
Revises: bb8a591d559c
Create Date: 2023-05-31 16:19:33.740658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b50aa3d4815'
down_revision = 'bb8a591d559c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('part_index',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('part_index',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
