"""intake_id

Revision ID: 81a63e3d033e
Revises: 244bd2d50413
Create Date: 2023-08-10 15:51:07.376062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a63e3d033e'
down_revision = '244bd2d50413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intake_id', sa.Integer(), nullable=True))
        batch_op.drop_column('reservation_name')
        batch_op.drop_column('reserved')
        batch_op.drop_column('reservation_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_time', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('reserved', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('reservation_name', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('intake_id')

    # ### end Alembic commands ###
