"""empty message

Revision ID: af9cc0f184df
Revises: 
Create Date: 2022-12-19 21:56:14.477371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9cc0f184df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residual_wood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(precision=2), nullable=False),
    sa.Column('width', sa.Float(precision=2), nullable=False),
    sa.Column('height', sa.Float(precision=2), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('density', sa.Float(precision=2), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('reservation_name', sa.String(length=80), nullable=True),
    sa.Column('reservation_time', sa.String(length=80), nullable=True),
    sa.Column('requirements', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('waste_wood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(precision=2), nullable=False),
    sa.Column('width', sa.Float(precision=2), nullable=False),
    sa.Column('height', sa.Float(precision=2), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('density', sa.Float(precision=2), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('damaged', sa.Boolean(), nullable=False),
    sa.Column('stained', sa.Boolean(), nullable=False),
    sa.Column('contains_metal', sa.Boolean(), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('reservation_name', sa.String(length=80), nullable=True),
    sa.Column('reservation_time', sa.String(length=80), nullable=True),
    sa.Column('requirements', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_wood')
    op.drop_table('tags')
    op.drop_table('residual_wood')
    # ### end Alembic commands ###
