"""add design geometry & project table

Revision ID: b53046738541
Revises: bb181750300a
Create Date: 2024-12-04 01:20:28.584098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53046738541'
down_revision = 'bb181750300a'
branch_labels = None
depends_on = None


def upgrade():
    # Create the projects table
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('client', sa.String(), nullable=True),
        sa.Column('design_geometry_count', sa.Integer(), nullable=True),
        sa.Column('parts_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )

    # Create the design_geometries table
    op.create_table(
        'design_geometries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_design_geometries_project_id_projects')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_design_geometries'))
    )

    # Add new columns to the requirements table
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('part_file_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('design_geometry_id', sa.Integer(), nullable=True))

    # Populate default values for project_id and design_geometry_id
    op.execute("UPDATE requirements SET project_id = 0 WHERE project_id IS NULL")
    op.execute("UPDATE requirements SET design_geometry_id = 0 WHERE design_geometry_id IS NULL")

    # Alter columns to make them NOT NULL
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.alter_column('design_geometry_id', nullable=False)
        batch_op.alter_column(
            'project_id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            nullable=False
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_requirements_design_geometry_id_design_geometries'),
            'design_geometries',
            ['design_geometry_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_requirements_project_id_projects'),
            'projects',
            ['project_id'],
            ['id']
        )
        batch_op.drop_column('part_index')
        batch_op.drop_column('features')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('part_index', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_requirements_project_id_projects'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_requirements_design_geometry_id_design_geometries'), type_='foreignkey')
        batch_op.alter_column('project_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('design_geometry_id')
        batch_op.drop_column('part_file_path')
        batch_op.drop_column('part_name')

    op.drop_table('design_geometries')
    op.drop_table('projects')
    # ### end Alembic commands ###
