"""update history table

Revision ID: b6d36fd7ece2
Revises: b53046738541
Create Date: 2024-12-16 18:46:18.430825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d36fd7ece2'
down_revision = 'b53046738541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_geometries', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requirement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_history_requirement_id_requirements'), 'requirements', ['requirement_id'], ['id'])

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('design_geometry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('design_geometry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_history_requirement_id_requirements'), type_='foreignkey')
        batch_op.drop_column('requirement_id')
        batch_op.drop_column('success')
        batch_op.drop_column('name')

    with op.batch_alter_table('design_geometries', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
