"""offset in production

Revision ID: bb181750300a
Revises: e43c80e5918d
Create Date: 2024-04-16 17:48:16.282702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb181750300a'
down_revision = 'e43c80e5918d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_column('offset')

    # ### end Alembic commands ###
