"""adds new fields Drako

Revision ID: bb671a77b435
Revises: 81a63e3d033e
Create Date: 2023-09-29 16:11:55.848404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb671a77b435'
down_revision = '81a63e3d033e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reservation_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('reservation_time', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('wood_species', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paint', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_fire_treated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_straight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_planed', sa.Boolean(), nullable=True))
        batch_op.drop_column('intake_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residual_wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intake_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_planed')
        batch_op.drop_column('is_straight')
        batch_op.drop_column('is_fire_treated')
        batch_op.drop_column('project_type')
        batch_op.drop_column('paint')
        batch_op.drop_column('label')
        batch_op.drop_column('wood_species')
        batch_op.drop_column('reservation_time')
        batch_op.drop_column('reservation_name')
        batch_op.drop_column('reserved')

    # ### end Alembic commands ###
