"""adds requirements

Revision ID: bc60b5aa7cbc
Revises: 4cb118f5865f
Create Date: 2023-05-17 16:59:30.225240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc60b5aa7cbc'
down_revision = '4cb118f5865f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements_from_dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_index', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('width', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.Column('part', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements_from_grasshopper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_index', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('width', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.Column('part', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('woods_requirements_dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wood_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements_from_dashboard.id'], ),
    sa.ForeignKeyConstraint(['wood_id'], ['residual_wood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('woods_requirements_gh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wood_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements_from_grasshopper.id'], ),
    sa.ForeignKeyConstraint(['wood_id'], ['residual_wood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('requirements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_index', sa.VARCHAR(), nullable=False),
    sa.Column('length', sa.VARCHAR(), nullable=False),
    sa.Column('width', sa.VARCHAR(), nullable=False),
    sa.Column('height', sa.VARCHAR(), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=80), nullable=True),
    sa.Column('part', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('woods_requirements_gh')
    op.drop_table('woods_requirements_dashboard')
    op.drop_table('requirements_from_grasshopper')
    op.drop_table('requirements_from_dashboard')
    # ### end Alembic commands ###
