"""empty message

Revision ID: d0908af99bdb
Revises: 68d04a7ca5be
Create Date: 2022-12-01 12:21:14.074375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0908af99bdb'
down_revision = '68d04a7ca5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residual_wood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(precision=2), nullable=False),
    sa.Column('width', sa.Float(precision=2), nullable=False),
    sa.Column('height', sa.Float(precision=2), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('density', sa.Float(precision=2), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_wood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(precision=2), nullable=False),
    sa.Column('width', sa.Float(precision=2), nullable=False),
    sa.Column('height', sa.Float(precision=2), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('density', sa.Float(precision=2), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('damaged', sa.Boolean(), nullable=False),
    sa.Column('stained', sa.Boolean(), nullable=False),
    sa.Column('contains_metal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wood_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wood_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('length', sa.FLOAT(), nullable=False),
    sa.Column('width', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('density', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=80), nullable=False),
    sa.Column('contains_metal', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('waste_wood')
    op.drop_table('residual_wood')
    # ### end Alembic commands ###
