"""subwood in production

Revision ID: e43c80e5918d
Revises: 3e3fb60b7371
Create Date: 2024-04-16 17:09:36.641109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43c80e5918d'
down_revision = '3e3fb60b7371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_wood_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_production_sub_wood_id_sub_wood'), 'sub_wood', ['sub_wood_id'], ['id'])

    with op.batch_alter_table('wood', schema=None) as batch_op:
        batch_op.drop_column('project_label')
        batch_op.drop_column('project_type')
        batch_op.drop_column('current_id')
        batch_op.drop_column('subsequent_id')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('subsequent_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('current_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('project_label', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_production_sub_wood_id_sub_wood'), type_='foreignkey')
        batch_op.drop_column('sub_wood_id')

    # ### end Alembic commands ###
